### ISSUE TITLE
FLEX: Combination of Group Message and Fragmentation

### ISSUE THREAD

**Issue by eopo** [EliasOenal/multimon-ng#155]
Hello,

i'm contributor with github.com/pagermon/pagermon. Recent changes in multimon introduced FLEX group messages to be shown as one message, instead of single messages for each address.
How would multimon output a message, that is fragmented and directed to multiple addresses?
Is it possible, that different fragments of the same message could have different addresses, or do all fragments of one message inevitably have the same addresses?

**Comment by Zanoroy** [comment]
The fragments will use the same Message address

**Comment by Zanoroy** [comment]
@eopo 
I have modified the flex code here [https://github.com/Zanoroy/multimon-ng](https://github.com/Zanoroy/multimon-ng) relating to ticket #153 that (if compiled with the GroupCalls variable set to 0) the group messages will print on each line rather than a single line with multiple capcodes.

I think we can close this ticket after this change is tested and I create a Pull Request

**Comment by eopo** [comment]
When the messages will always be the same, it'll work just fine even with group messages outputted as one string. Just worried that they might have different subsets, which would have made it hard to handle, when shown in one string.
