### ISSUE TITLE
Timestamp

### ISSUE THREAD

**Issue by unwichtig** [EliasOenal/multimon-ng#46]
It would be great to have a timestamp in every line which is encoded.
I needed 2 days of playing till i got Messages, but now it works very fine with Pocsag512 and Pocsag1200.

**Comment by patVog** [comment]
I plan to implement this. @EliasOenal what do you think is the better way to do it. I can modify the _verbprintf function in unixinput.c or add a time stamp to each format string?

**Comment by EliasOenal** [comment]
I think _verbprintf is probably the way to go, since this would otherwise be transparent for the decoders. Also I would recommend using getopt long (e.g. '--timestamp') since '-t' is already taken and there aren't too many unused short parameters left.
https://www.gnu.org/software/libc/manual/html_node/Getopt-Long-Option-Example.html
