### ISSUE TITLE
FLEX fragmented messages

### ISSUE THREAD

**Issue by Shaggs** [EliasOenal/multimon-ng#52]
First things first thanks for making a program that can decode FLEX so i can decode using a raspberry pi.

one slight problem is fragmented messages are not handled.

when a message   is sent using FLEX and gets broken up along the way the bitrate changes from 1600 to 1601 if fragmented once and goes up depending on fragmented amount.

in PDW this bitrate change is picked up.

below is output from PDW 

CAPCODE  TIME     DATE        BITRATE   MESSGAE
1931416 02:06:43 20-09-16 1600  MFS: *CFSRES INC0003 20/09/16 02:06 RESPOND PRIVATE ALARM, ALARM LEVEL: 1, : @SMITHFIELD 
                                - MFS Elizabeth Station -

1931416 02:06:45 20-09-16 1601  PLAINS HIGH SCHOOL 1 BEAUMONT RD SMITHFIELD PLAINS,MAP:ADL 42 B13,TG C163 T183, :ELZ331 ELZ339 SAL321 :
                                - MFS Elizabeth Station -

as you can see the second one as a bitrate of 1601 (pager gets this as one message)

here is the output from multimon

Date              Time        CAPCODE      BITRATE     MESSAGE
2016-09-20 02:06:45  [001931416] 1600/2/A PLAINS HIGH SCHOOL 1 BEAUMONT RD SMITHFIELD PLAINS,MAP:ADL 42 B13,TG C163 T183, :ELZ331 ELZ339 SAL321 :

as you can see the first part of message  is missing as its not a 1600 bitrate

full logs available if required

**Comment by pvachon** [comment]
After spending some quality time debugging this issue in the FLEX decoder for my own project, I actually think it's traceable to three things

 * Aggressive fragmentation by the pager operator (FWIW, I'm not sure if PDW handles fragmentation automatically or not),
 * Quirky behavior in demod_flex.c to handle sampling the signal (since 22050 Hz is not an even multiple of 1600, some acrobatics need to be done), which seems to have a hard time staying in sync and, most importantly,
 * The DC blocking filter causing the signal levels to be consistently lower/higher than expected. This means symbol decoding can sometimes be way off, and the BCH(31, 21) code isn't able to fix that many errors. I've observed this is really bad after a period of low traffic. You'll typically miss that entire frame. Subsequent frames will decode well enough, though.

All these factors contribute to the problems you're seeing, I believe. I have another FLEX decoder I've been working on, that I plan to possibly integrate back into Multimon, you can find it in my GitHub projects. I don't want to advertise another project here though. :-)

**Comment by Zanoroy** [comment]
@Shaggs I'd be interested in so of your raw data if you have any. I managed to fix the multi-part message issues when porting the flex code to c#, I went through two primary issues identified. If you read through the issues I raised #63 (sorry I could have continued it here but @pvachon description didnt seem to jell with my findings) . Hopefully these two small changes to the demod_flex.c will resolve your issues.

**Comment by Shaggs** [comment]
@Zanoroy ill reccored shortly and upload to dropbox how much do you want?

**Comment by Shaggs** [comment]
or if you could post you pull requests i xan run it along side my windows pc running pdw

**Comment by Shaggs** [comment]
https://www.dropbox.com/s/l5aqj6jjsr3ecl4/Pdw%20Fragmented.m4a?dl=0

will be up for 3 hrs from now

**Comment by Shaggs** [comment]
https://www.dropbox.com/s/l5aqj6jjsr3ecl4/Pdw%20Fragmented.m4a?dl=0

will be up for 3 hrs from now

**Comment by Shaggs** [comment]
or if you could post you pull requests i xan run it along side my windows pc running pdw

**Comment by Zanoroy** [comment]
Sorry, the code fix I put in place is actually in c# I haven't 'pulled' it officially, I can test the code a lot easier in Visual Studio where I can walk the symbols one by one. 
Your 8 minutes of data should be good enough for me to play with.

I'll let you know how i go.

**Comment by Shaggs** [comment]
will this work on linux?

**Comment by Zanoroy** [comment]
Yes I can give you the single file, you will have to recompile but that will be all. Are you in Adelaide? if so, I did this fix using the Adelaide (I'm in Vales Park) flex network. I'm also part of the team rolling out the new Paging network.

**Comment by Shaggs** [comment]
yes i am in the hills not sure how to pm on here but very interested in what is to come and would like to work along side as i have a few things i use the paging for (turnout systems)

**Comment by Zanoroy** [comment]
Ok,  the fix I have in place gets exactly the same messages as PDW does.

Let me convert it to the Linux version and upload it (it will take about 5 minutes)

**Comment by Zanoroy** [comment]
I have attached the the demod_flex.c replacement file that fixes the issues (I have to zip it to be able to upload it to github)

Unzip it and copy over the existing one and recompile multimon-ng and your issues will be solved.
Not sure we can PM here but my email address is zanoroy@gmail.com feel free to email me and we can chat, I'm assuming you are working with CFS?

[demod_flex.zip](https://github.com/EliasOenal/multimon-ng/files/1040291/demod_flex.zip)

**Comment by Zanoroy** [comment]
I have an improved version.

**Comment by Shaggs** [comment]
can you post or email updated version till try it overnight..

**Comment by jklnz** [comment]
Use this demod_flex.c and recompile it
[demod_flex.zip](https://github.com/EliasOenal/multimon-ng/files/1044252/demod_flex.zip)

**Comment by Shaggs** [comment]
Closing Issue as #63 fixed issue.
